# Generated by Django 3.2.5 on 2022-01-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Labname', models.CharField(default='', max_length=200)),
                ('img', models.ImageField(default='', upload_to='lablogo/')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
                ('Address', models.TextField(default='', max_length=300)),
                ('Home_Sample', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=200, null=True)),
            ],
        ),
    ]
