# Generated by Django 3.2.5 on 2022-01-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocomplete_search', '0002_remove_lab_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='password',
        ),
    ]
